### PR TITLE
Add wordcounting

### PR DESCRIPTION
**Pull request by heukirne**
Solve issue https://github.com/sharelatex/web-sharelatex/issues/4

### CODE REVIEW

**Comment by briangough** [comment]
This looks good - the only change I think we should make is to move the running of texcount inside the docker container for safety.  This means replacing   

    child_process.exec  "texcount", args, timeout: 10 * seconds, (error, stdout, stderr) ->

with a call to 

    CommandRunner.run project_id, command, directory, timeout, callback

We have 'texcount' in the docker image already so it should be a simple replacement of the commands. The one difference is to write the output from texcount into a file using "-out=wordcount.out" (or something like that)  and read it to get the results,  only because our current implementation of CommandRunner does not pass back stdout.

**Comment by heukirne** [comment]
Hi @briangough, I'm just waiting @henryoswald answer about that on email. Could you ask him?

**Comment by henryoswald** [comment]
@heukirne yes please make these changes when you have time.

**Comment by heukirne** [comment]
Done!

**Comment by henryoswald** [comment]
added some commits via https://github.com/sharelatex/clsi-sharelatex/pull/33

**Pull request closed without merging**
