### PR TITLE
Add a 1 second delay to the smoke tests

### PR DESCRIPTION
**Pull request by mrjgreen**
Fixes a race condition where smoke tests exit before container can be attached to.

See here for more info: https://github.com/overleaf/sharelatex/issues/274

### CODE REVIEW

**Comment by jpallen** [comment]
I can't seem to get this code to sleep when I run it on www.sharelatex.com :(

**Comment by jpallen** [comment]
Feel free to play around: https://www.sharelatex.com/3168193932xttbwjtrqbpb

**Comment by mrjgreen** [comment]
Can't really add much to this. What was the other solution you suggested where we remove the lock file in the smoke test?

**Comment by jdleesmiller** [comment]
Do we have a feel for how much work would it be to fix the race condition? The approach seems pretty clear to me (https://github.com/overleaf/sharelatex/issues/274#issuecomment-348683728), unless I am missing something. Just want to make sure we don't spend more time on the mitigation than the fix.

**Comment by jpallen** [comment]
> Do we have a feel for how much work would it be to fix the race condition?

Not really, but I suspect quite a bit, mainly in re-loading the mental model of what the CLSI is doing. There was a reason that we did all the steps of `run` manually, rather than just using that API, but I can't recall what it was. Possibly `run` didn't exist in dockerode at the time, or we wanted to be more creative with container reuse, and `run` didn't allow that (but this was again to work around memory leaks in early versions of docker with lots of containers). Changing to `run` would involve looking at all the logic around how we manage containers again.

**Comment by henryoswald** [comment]
rather than doing a sleep, could just give the latex a bit of work todo, a small TikZ?

**Comment by jdleesmiller** [comment]
> Not really, but I suspect quite a bit

OK, I can appreciate the need to avoid the alerts. I think Henry's suggestion is a good one. Lots to choose from on texample.net if we need one.

**Comment by jdleesmiller** [comment]
Here's an example: https://www.sharelatex.com/1433366646rfxypvrnmyzv

**Comment by henryoswald** [comment]
I've modified your project @jdleesmiller to make the compile faster, watching it on the clsi it now takes about 1.3 seconds vs 5 seconds before

**Comment by mrjgreen** [comment]
well spotted, thanks John!

**Pull request merged**
