### PR TITLE
Bump node to 6.15

### PR DESCRIPTION
**Pull request by mans0954**
Related to: https://github.com/overleaf/sharelatex/issues/1309

### CODE REVIEW

**Comment by jdleesmiller** [comment]
We should still have an `npm-shrinkwrap.json` even though we don't have a `package-lock.json`; the former is supported in npm 3 as well as 5, and the latter is supported in 5+.

You can generate it by running `npm shrinkwrap --dev` in the container.

**Comment by 40thieves** [comment]
I need to properly research this, but I believe it's preferable to have a `package-lock.json` with npm5+ than an `npm-shrinkwrap.json`. There is some nuance about which to use when.

Although at least in current versions of npm I think they are identical formats, so it may be possible to just `mv npm-shrinkwrap.json package-lock.json`.

**Comment by jdleesmiller** [comment]
Yes, once we transition to npm5+, we should probably move to `package-lock.json` instead of `npm-shrinkwrap.json`. However, until we are on npm5+ everywhere, `npm-shrinkwrap.json` has the useful property of working on older versions of npm.

**Comment by mans0954** [comment]
I've added a `npm-shrinkwrap.json` for now.

**Pull request merged**
